development:
  adapter: mysql
  encoding: utf8
  database: cards_development
  username: root
  password:
  socket: /tmp/mysql.sock

test: &TEST
  adapter: mysql
  encoding: utf8
  database: cards_test
  username: root
  password:
  socket: /tmp/mysql.sock

#slicehost
# production:
#   adapter: mysql
#   encoding: utf8
#   database: cards_production
#   username: cards
#   password: xxx
#   socket: /var/run/mysqld/mysqld.sock
    
staging:
  <<: *PRODUCTION
  
cucumber:
  <<: *TEST